Initial API
awesome-academy/HN_Pra19_Android_Weather_App pull request #5
Opened 2024-07-25 01:48 UTC by DungTheRipper

## Related Tickets
- [#Task 78286: Initial API](https://edu-redmine.sun-asterisk.vn/issues/xxxx)
## WHAT
- Create base API and models from weatherapi.com
## Evidence (Screenshot or Video)

## Review Checklist

Category | View Point | Description | Self review | Reviewer2 (name)
--- | --- | --- | --- | ---
Conventions | Sun* coding conventions | https://sal.vn/WtYPAy |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Conventions | Kotlin coding conventions | https://kotlinlang.org/docs/coding-conventions.html |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Redmine | Sun* Redmine working process  | https://sal.vn/piPoQn |<li>- [ ] yes</li>|<li>- [ ] yes</li>  

## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(List gem, library third party add new)*

*(Other notes)*

2024-07-25 01:52 UTC, ireone01 approved these changes

2024-07-25 01:52 UTC, Hoaivuxuan approved these changes

2024-07-26 06:11 UTC, gianghv-3456 requested changes
pls check my cmts

2024-07-26 06:11 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/utils/Constant.kt
> +    const val BASE_API_KEY = "key=" + "4abd7b21910340fd889235405242307"
Không cộng string ở hằng số, để việc cộng string khi build URL
```suggestion
    const val BASE_API_KEY = "4abd7b21910340fd889235405242307"
```

2024-07-26 06:11 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/remote/fetchJson/ParseJson.kt
> +    }
Nếu là Utils function viết ở dạng "static" em nên viết thành **Top-level** để tránh việc khởi tạo bộ nhớ nhiều lần (do viết thành class)

2024-07-26 06:11 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/remote/fetchJson/ParseDataWithJson.kt
> +}
Sử dụng GSON đi em

2024-07-26 06:11 UTC, gianghv-3456 commented on app/src/main/java/com/example/sun/data/repository/source/remote/fetchJson/GetJsonFromUrl.kt
> +    }
Cái gì thế này??????
Tại sao class để handle mạng lại có init. Hãy để các hàm được gọi khi các tầng khác (repository, data source) cần chúng, không init thế này

2024-07-30 07:19 UTC, gianghv-3456 approved these changes

2024-07-30 07:19 UTC, merged